

import java.awt.HeadlessException;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import products.Entry;
import java.util.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
public class MobileAndTabs extends javax.swing.JFrame {
    static int i=0;
    /**
     * Creates new form MobileAndTabs
     */
    
    PreparedStatement pst;
    Connection conn;
    public MobileAndTabs() {
         super("Mobile&Tabs");
        initComponents();
        conn=JavaConnect.ConnecrDB();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        ONEPLUS = new javax.swing.JLabel();
        ONEPLUS_6T = new javax.swing.JLabel();
        onep_price = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        onep_description = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        apple = new javax.swing.JLabel();
        iphonex = new javax.swing.JLabel();
        iphonex_price = new javax.swing.JLabel();
        iphonex_descrip = new javax.swing.JLabel();
        iphoneadd = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        honor = new javax.swing.JLabel();
        honor8x = new javax.swing.JLabel();
        honor_price = new javax.swing.JLabel();
        honor_descrip = new javax.swing.JLabel();
        honoradd = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        apple2 = new javax.swing.JLabel();
        ipad = new javax.swing.JLabel();
        ipad_price = new javax.swing.JLabel();
        ipad_descrip = new javax.swing.JLabel();
        ipadbutton = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lg = new javax.swing.JLabel();
        lg_model = new javax.swing.JLabel();
        lg_price = new javax.swing.JLabel();
        lg_descrip = new javax.swing.JLabel();
        lgbutton = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        nova = new javax.swing.JLabel();
        nova_model = new javax.swing.JLabel();
        nova_price = new javax.swing.JLabel();
        nova_descrip = new javax.swing.JLabel();
        novabutton = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jbl = new javax.swing.JLabel();
        jbl_model = new javax.swing.JLabel();
        jbl_price = new javax.swing.JLabel();
        jbl_descrip = new javax.swing.JLabel();
        jblbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(0, 0, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("EKART");

        jButton2.setText("MY CART");
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(83, 83, 83))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton2)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PHOTO");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("BRAND");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MODEL");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PRICE");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("DESCRIPTION");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/products/pics/Oneplus_6_L_1new.jpg"))); // NOI18N

        ONEPLUS.setText("ONEPLUS");

        ONEPLUS_6T.setText("ONEPLUS 6T");

        onep_price.setText("34,699");

        jButton1.setText("ADD");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        onep_description.setText("Mirror Black 6GB RAM 128GB Storage");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(ONEPLUS)
                .addGap(74, 74, 74)
                .addComponent(ONEPLUS_6T)
                .addGap(76, 76, 76)
                .addComponent(onep_price)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(onep_description)
                .addGap(35, 35, 35)
                .addComponent(jButton1)
                .addGap(26, 26, 26))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ONEPLUS)
                    .addComponent(ONEPLUS_6T)
                    .addComponent(onep_price)
                    .addComponent(onep_description)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/products/pics/download (1).jpg"))); // NOI18N

        apple.setText("APPLE");

        iphonex.setText("iPhoneX");

        iphonex_price.setText("87999");

        iphonex_descrip.setText("Matt Black, 64/128GB storage,4GB RAM");

        iphoneadd.setText("ADD");
        iphoneadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iphoneaddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(apple)
                .addGap(79, 79, 79)
                .addComponent(iphonex)
                .addGap(86, 86, 86)
                .addComponent(iphonex_price)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iphonex_descrip)
                .addGap(18, 18, 18)
                .addComponent(iphoneadd)
                .addGap(29, 29, 29))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apple)
                    .addComponent(iphonex)
                    .addComponent(iphonex_price)
                    .addComponent(iphonex_descrip)
                    .addComponent(iphoneadd))
                .addContainerGap(77, Short.MAX_VALUE))
            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/products/pics/honor.jpg"))); // NOI18N

        honor.setText("HONOR");

        honor8x.setText("HONOR 8X");

        honor_price.setText("33599");

        honor_descrip.setText("Black,4GB RAM,64 GB Sorage ");

        honoradd.setText("ADD");
        honoradd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                honoraddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(honor)
                .addGap(71, 71, 71)
                .addComponent(honor8x)
                .addGap(75, 75, 75)
                .addComponent(honor_price)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(honor_descrip)
                .addGap(36, 36, 36)
                .addComponent(honoradd)
                .addGap(21, 21, 21))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(honor)
                    .addComponent(honor8x)
                    .addComponent(honor_price)
                    .addComponent(honor_descrip)
                    .addComponent(honoradd))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/products/pics/ipadpro.jpg"))); // NOI18N

        apple2.setText("APPLE");

        ipad.setText("IPAD PR0");

        ipad_price.setText("55699");

        ipad_descrip.setText("BLACK, 4GB RAM,256GB STORAGE");

        ipadbutton.setText("ADD");
        ipadbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipadbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel23)
                .addGap(51, 51, 51)
                .addComponent(apple2)
                .addGap(73, 73, 73)
                .addComponent(ipad)
                .addGap(82, 82, 82)
                .addComponent(ipad_price)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ipad_descrip)
                .addGap(18, 18, 18)
                .addComponent(ipadbutton)
                .addGap(20, 20, 20))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apple2)
                    .addComponent(ipad)
                    .addComponent(ipad_price)
                    .addComponent(ipad_descrip)
                    .addComponent(ipadbutton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/products/pics/TV1.jpg"))); // NOI18N

        lg.setText("LG");

        lg_model.setText("32T8361HD TV");

        lg_price.setText("37599");

        lg_descrip.setText("27 inch OLED Display,Bluetooth");

        lgbutton.setText("ADD");
        lgbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lgbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(44, 44, 44)
                .addComponent(lg)
                .addGap(80, 80, 80)
                .addComponent(lg_model)
                .addGap(64, 64, 64)
                .addComponent(lg_price)
                .addGap(80, 80, 80)
                .addComponent(lg_descrip)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lgbutton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lg)
                    .addComponent(lg_model)
                    .addComponent(lg_price)
                    .addComponent(lg_descrip)
                    .addComponent(lgbutton)))
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/products/pics/TRIMMER.jpeg"))); // NOI18N

        nova.setText("NOVA");

        nova_model.setText("NHT 1085");

        nova_price.setText("1599");

        nova_descrip.setText("Black/Blue cordless electric trimmer");

        novabutton.setText("ADD");
        novabutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novabuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel14)
                .addGap(120, 120, 120)
                .addComponent(nova)
                .addGap(83, 83, 83)
                .addComponent(nova_model)
                .addGap(88, 88, 88)
                .addComponent(nova_price)
                .addGap(57, 57, 57)
                .addComponent(nova_descrip)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(novabutton)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addContainerGap())
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nova)
                    .addComponent(nova_model)
                    .addComponent(nova_price)
                    .addComponent(nova_descrip)
                    .addComponent(novabutton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/products/pics/EAR.jpg"))); // NOI18N

        jbl.setText("JBL");

        jbl_model.setText("C00S1");

        jbl_price.setText("1,999");

        jbl_descrip.setText("Black Earphones with mic");

        jblbutton.setText("ADD");
        jblbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addGap(59, 59, 59)
                .addComponent(jbl)
                .addGap(100, 100, 100)
                .addComponent(jbl_model)
                .addGap(98, 98, 98)
                .addComponent(jbl_price)
                .addGap(95, 95, 95)
                .addComponent(jbl_descrip)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jblbutton)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(21, 21, 21))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbl)
                    .addComponent(jbl_model)
                    .addComponent(jbl_price)
                    .addComponent(jbl_descrip)
                    .addComponent(jblbutton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(157, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1276, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(865, 1347));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void iphoneaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iphoneaddActionPerformed
        // TODO add your handling code here:
        try
        {
            String sql="Insert into mobiletabs(brand,model,price,descrip) values (?,?,?,?)" ;
             pst=conn.prepareStatement(sql);
             pst.setString(1, apple.getText());
              pst.setString(2, iphonex.getText());
              pst.setString(3, iphonex_price.getText());
              pst.setString(4, iphonex_descrip.getText());
               pst.execute();
             //new cart(iphonex_price.getText(),apple.getText(),iphonex.getText(),iphonex_descrip.getText()).setVisible(true);
             Entry e = new Entry(iphonex_price.getText(),apple.getText(),iphonex.getText(),iphonex_descrip.getText());
             addToProductList(e); 
             
              
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        
    }//GEN-LAST:event_iphoneaddActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
           String sql="Insert into mobiletabs(brand,model,price,descrip) values (?,?,?,?)" ;
           pst=conn.prepareStatement(sql);
           pst.setString(1, ONEPLUS.getText());
           pst.setString(2, ONEPLUS_6T.getText());
           pst.setString(3, onep_price.getText());
           
           pst.setString(4, onep_description.getText());
          
           pst.execute();
            
           //rs.close();
           pst.close();
           //Items i=new Items(onep_price.getText(),ONEPLUS.getText(),ONEPLUS_6T.getText(),onep_description.getText());
           //new cart(onep_price.getText(),ONEPLUS.getText(),ONEPLUS_6T.getText(),onep_description.getText()).setVisible(true);
           Entry e = new Entry(onep_price.getText(),ONEPLUS.getText(),ONEPLUS_6T.getText(),onep_description.getText());
           addToProductList(e); 
             
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }/*finally*/
      
      
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void honoraddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_honoraddActionPerformed
        // TODO add your handling code here:
        try
        {
            String sql="Insert into mobiletabs(brand,model,price,descrip) values (?,?,?,?)" ;
             pst=conn.prepareStatement(sql);
              pst.setString(1, honor.getText());
              pst.setString(2, honor8x.getText());
              pst.setString(3, honor_price.getText());
              pst.setString(4, honor_descrip.getText());
              pst.execute();
              pst.close();
              //new cart(honor_price.getText(),honor.getText(),honor8x.getText(),honor_descrip.getText()).setVisible(true);
              Entry e = new Entry(honor_price.getText(),honor.getText(),honor8x.getText(),honor_descrip.getText());
              addToProductList(e); 
             
             
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_honoraddActionPerformed

    private void ipadbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipadbuttonActionPerformed
        // TODO add your handling code here:
        try
        {
            String sql="Insert into mobiletabs(brand,model,price,descrip) values (?,?,?,?)" ;
             pst=conn.prepareStatement(sql);
             pst.setString(1, apple2.getText());
              pst.setString(2, ipad.getText());
               pst.setString(3, ipad_price.getText());
                pst.setString(4, ipad_descrip.getText());
                pst.execute();
                pst.close();
                //new cart(ipad_price.getText(),apple2.getText(),ipad.getText(),ipad_descrip.getText()).setVisible(true);
               Entry e = new Entry(ipad_price.getText(),apple2.getText(),ipad.getText(),ipad_descrip.getText());
               addToProductList(e); 
             
              
             
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_ipadbuttonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       // TODO add your handling code here:
        setVisible(false);
       cart c = new cart(v,i);
        c.setVisible(true);
        JOptionPane.showMessageDialog(null,"cartpge");
      
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void lgbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lgbuttonActionPerformed
        // TODO add your handling code here:
        try
        {
            String sql="Insert into mobiletabs(brand,model,price,descrip) values (?,?,?,?)" ;
            pst=conn.prepareStatement(sql);
            pst.setString(1, lg.getText());
            pst.setString(2, lg_model.getText());
            pst.setString(3, lg_price.getText());
            pst.setString(4, lg_descrip.getText());
            pst.execute();
                pst.close();
                
            Entry e = new Entry(lg_price.getText(),lg.getText(),lg_model.getText(),lg_descrip.getText());
               addToProductList(e);
            
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_lgbuttonActionPerformed

    private void novabuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novabuttonActionPerformed
        // TODO add your handling code here:
        try
        {
            String sql="Insert into mobiletabs(brand,model,price,descrip) values (?,?,?,?)" ;
             pst=conn.prepareStatement(sql);
             
             pst.setString(1, nova.getText());
             pst.setString(2, nova_model.getText());
            pst.setString(3, nova_price.getText());
            pst.setString(4, nova_descrip.getText());
             pst.execute();
                pst.close();
                 Entry e = new Entry(nova_price.getText(),nova.getText(),nova_model.getText(),nova_descrip.getText());
               addToProductList(e);
                
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_novabuttonActionPerformed

    private void jblbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblbuttonActionPerformed
        // TODO add your handling code here:
        try
        {
            String sql="Insert into mobiletabs(brand,model,price,descrip) values (?,?,?,?)" ;
             pst=conn.prepareStatement(sql);
             pst.setString(1, jbl.getText());
             pst.setString(2, jbl_model.getText());
             pst.setString(3, jbl_price.getText());
             pst.setString(4, jbl_descrip.getText());
              pst.execute();
                pst.close();
                Entry e = new Entry(jbl_price.getText(),jbl.getText(),jbl_model.getText(),jbl_descrip.getText());
               addToProductList(e);
                
             
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jblbuttonActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MobileAndTabs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MobileAndTabs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MobileAndTabs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MobileAndTabs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MobileAndTabs().setVisible(true);
            }
        });
    }
    Vector<Entry> v = new Vector<>();
    
    public void addToProductList(Entry e){
        i++;
        v.addElement(e);
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel ONEPLUS;
    public javax.swing.JLabel ONEPLUS_6T;
    private javax.swing.JLabel apple;
    private javax.swing.JLabel apple2;
    private javax.swing.JLabel honor;
    private javax.swing.JLabel honor8x;
    private javax.swing.JLabel honor_descrip;
    private javax.swing.JLabel honor_price;
    private javax.swing.JButton honoradd;
    private javax.swing.JLabel ipad;
    private javax.swing.JLabel ipad_descrip;
    private javax.swing.JLabel ipad_price;
    private javax.swing.JButton ipadbutton;
    private javax.swing.JButton iphoneadd;
    private javax.swing.JLabel iphonex;
    private javax.swing.JLabel iphonex_descrip;
    private javax.swing.JLabel iphonex_price;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jbl;
    private javax.swing.JLabel jbl_descrip;
    private javax.swing.JLabel jbl_model;
    private javax.swing.JLabel jbl_price;
    private javax.swing.JButton jblbutton;
    private javax.swing.JLabel lg;
    private javax.swing.JLabel lg_descrip;
    private javax.swing.JLabel lg_model;
    private javax.swing.JLabel lg_price;
    private javax.swing.JButton lgbutton;
    private javax.swing.JLabel nova;
    private javax.swing.JLabel nova_descrip;
    private javax.swing.JLabel nova_model;
    private javax.swing.JLabel nova_price;
    private javax.swing.JButton novabutton;
    private javax.swing.JLabel onep_description;
    private javax.swing.JLabel onep_price;
    // End of variables declaration//GEN-END:variables
}
